# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulumi/engine/engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pulumi import plugin_pb2 as pulumi_dot_plugin__pb2
from pulumi import language_pb2 as pulumi_dot_language__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apulumi/engine/engine.proto\x12\x10pulumirpc.engine\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13pulumi/plugin.proto\x1a\x15pulumi/language.proto\"=\n\x0c\x41\x62outRequest\x12\r\n\x05stack\x18\x01 \x01(\t\x12\x1e\n\x16transitiveDependencies\x18\x02 \x01(\x08\"N\n\x0c\x41\x62outBackend\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x15\n\rorganizations\x18\x04 \x03(\t\"\'\n\nAboutState\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03urn\x18\x02 \x01(\t\"\x84\x01\n\nAboutStack\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\tresources\x18\x02 \x03(\x0b\x32\x1c.pulumirpc.engine.AboutState\x12\x37\n\x11pendingOperations\x18\x03 \x03(\x0b\x32\x1c.pulumirpc.engine.AboutState\"\xd1\x02\n\rAboutResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x11\n\tgoVersion\x18\x02 \x01(\t\x12\x12\n\ngoCompiler\x18\x03 \x01(\t\x12,\n\x07plugins\x18\x04 \x03(\x0b\x32\x1b.pulumirpc.PluginDependency\x12\x0f\n\x07runtime\x18\x05 \x01(\t\x12*\n\x08language\x18\x06 \x01(\x0b\x32\x18.pulumirpc.AboutResponse\x12/\n\x0c\x64\x65pendencies\x18\x07 \x03(\x0b\x32\x19.pulumirpc.DependencyInfo\x12/\n\x07\x62\x61\x63kend\x18\x08 \x01(\x0b\x32\x1e.pulumirpc.engine.AboutBackend\x12+\n\x05stack\x18\t \x01(\x0b\x32\x1c.pulumirpc.engine.AboutStack\x12\x0e\n\x06\x65rrors\x18\n \x03(\t2T\n\x06\x45ngine\x12J\n\x05\x41\x62out\x12\x1e.pulumirpc.engine.AboutRequest\x1a\x1f.pulumirpc.engine.AboutResponse\"\x00\x42\x31Z/github.com/pulumi/pulumi/sdk/v3/proto/go/engineb\x06proto3')



_ABOUTREQUEST = DESCRIPTOR.message_types_by_name['AboutRequest']
_ABOUTBACKEND = DESCRIPTOR.message_types_by_name['AboutBackend']
_ABOUTSTATE = DESCRIPTOR.message_types_by_name['AboutState']
_ABOUTSTACK = DESCRIPTOR.message_types_by_name['AboutStack']
_ABOUTRESPONSE = DESCRIPTOR.message_types_by_name['AboutResponse']
AboutRequest = _reflection.GeneratedProtocolMessageType('AboutRequest', (_message.Message,), {
  'DESCRIPTOR' : _ABOUTREQUEST,
  '__module__' : 'pulumi.engine.engine_pb2'
  # @@protoc_insertion_point(class_scope:pulumirpc.engine.AboutRequest)
  })
_sym_db.RegisterMessage(AboutRequest)

AboutBackend = _reflection.GeneratedProtocolMessageType('AboutBackend', (_message.Message,), {
  'DESCRIPTOR' : _ABOUTBACKEND,
  '__module__' : 'pulumi.engine.engine_pb2'
  # @@protoc_insertion_point(class_scope:pulumirpc.engine.AboutBackend)
  })
_sym_db.RegisterMessage(AboutBackend)

AboutState = _reflection.GeneratedProtocolMessageType('AboutState', (_message.Message,), {
  'DESCRIPTOR' : _ABOUTSTATE,
  '__module__' : 'pulumi.engine.engine_pb2'
  # @@protoc_insertion_point(class_scope:pulumirpc.engine.AboutState)
  })
_sym_db.RegisterMessage(AboutState)

AboutStack = _reflection.GeneratedProtocolMessageType('AboutStack', (_message.Message,), {
  'DESCRIPTOR' : _ABOUTSTACK,
  '__module__' : 'pulumi.engine.engine_pb2'
  # @@protoc_insertion_point(class_scope:pulumirpc.engine.AboutStack)
  })
_sym_db.RegisterMessage(AboutStack)

AboutResponse = _reflection.GeneratedProtocolMessageType('AboutResponse', (_message.Message,), {
  'DESCRIPTOR' : _ABOUTRESPONSE,
  '__module__' : 'pulumi.engine.engine_pb2'
  # @@protoc_insertion_point(class_scope:pulumirpc.engine.AboutResponse)
  })
_sym_db.RegisterMessage(AboutResponse)

_ENGINE = DESCRIPTOR.services_by_name['Engine']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/pulumi/pulumi/sdk/v3/proto/go/engine'
  _ABOUTREQUEST._serialized_start=121
  _ABOUTREQUEST._serialized_end=182
  _ABOUTBACKEND._serialized_start=184
  _ABOUTBACKEND._serialized_end=262
  _ABOUTSTATE._serialized_start=264
  _ABOUTSTATE._serialized_end=303
  _ABOUTSTACK._serialized_start=306
  _ABOUTSTACK._serialized_end=438
  _ABOUTRESPONSE._serialized_start=441
  _ABOUTRESPONSE._serialized_end=778
  _ENGINE._serialized_start=780
  _ENGINE._serialized_end=864
# @@protoc_insertion_point(module_scope)
